services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"  # MinIO S3 API
      - "9001:9001"  # MinIO Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  minio-init:
    image: minio/mc
    container_name: minio-init
    depends_on:
      - minio
    volumes:
      - ./install/init-bucket.sh:/init-bucket.sh
    entrypoint: [ "/bin/sh", "-c", "chmod +x /init-bucket.sh && /init-bucket.sh" ]
    

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    depends_on:
      - minio
    volumes:
      - ./stripe-config:/root/.config/stripe
      - ./install/init_stripe.sh:/stripe-entrypoint.sh
      - ./application/src/main/resources/PAWA_BE_CN.pem:/usr/local/share/ca-certificates/my-ca.crt:ro
    entrypoint: [ "/bin/sh", "/stripe-entrypoint.sh" ]
    environment:
      STRIPE_API_KEY: sk_test_51RHDVRIsR1g5YtKwUR16rCyOeeReFFxFp50ZIRMfZDILke8iGK58Ip62QfO4kQNr0W94Z0TYvKVg8jwgIXOkhIN300C6pWFy9B
      STRIPE_CA_BUNDLE: /usr/local/share/ca-certificates/my-ca.crt
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    build: ./db
    container_name: 'pawa_postgres'
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: 'pawa_be_db'
      POSTGRES_USER: 'pawa_admin'
      POSTGRES_PASSWORD: '123'
    volumes:
      - '.postgres-data:/var/lib/postgresql/data'
      - './db:/docker-entrypoint-initdb.d'
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
#  spring-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: spring-app
#    ports:
#      - "8443:8443"
#    depends_on:
#      - postgres
#      - minio
#      - stripe-cli
#    environment:
#      SPRING_PROFILES_ACTIVE: dev
#      DB_URL: jdbc:postgresql://postgres:5432/pawa_be_db
#      DB_USER: pawa_admin
#      DB_PASSWORD: 123
#      OPWA_URL: http://host.docker.internal:8081
#      MINIO_URL: http://host.docker.internal:9000
#      FRONTEND_URL: http://localhost:3000
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

volumes:
  minio-data:
  postgres-data: